name: Build Autodex Simulator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Cloner le depot
        run: |
          git clone --depth=1 https://github.com/${{ github.repository }}.git .

      - name: Selectionner Xcode 16
        run: |
          sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer

      - name: Compilation de l'application
        run: |
          xcodebuild -project Autodex.xcodeproj \
            -scheme Autodex \
            -destination "generic/platform=iOS Simulator" \
            -configuration Debug \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Compression en ZIP
        run: |
          cd build/Build/Products/Debug-iphonesimulator/
          zip -r autodex-simulator.zip Autodex.app

      - name: Exporter le ZIP
        uses: actions/upload-artifact@v4
        with:
          name: autodex-simulator
          path: build/Build/Products/Debug-iphonesimulator/autodex-simulator.zip
